#!/usr/bin/env bash
#PBS -q omp
#PBS -l walltime=00:300:00
#PBS -l ncpus=4
#PBS -l mem=5g
#PBS -J 1-24

#This script is used to process 24 .fastq files in fastQC at the same time.

#Activating fastqc conda environment:
. /appli/bioinfo/fastqc/0.11.9/env.sh

#Input directory with yout fastq.gz files:
FASTQ_DIR=/home1/datawork/tsoldour/PESTO_methylseq/cutadapt/raw-Data

#Output directory for FastQC results:
FASTQC_OUT=$SCRATCH/trimmed-fastqc-array
mkdir -p $FASTQC_OUT

#Retrieving the file path according to the PBS index and its position in the list:
arrayfile=$(ls $FASTQ_DIR/*.fastq.gz | awk "NR==${PBS_ARRAY_INDEX}")

#Retrieving the basename of the file:
#filebasename=$(basename $arrayfile |sed 's/ .fastq.gz//g')
filebasename=$(basename ${arrayfile%.fastq*})

#To get the log output in the same place:
cd $PBS_O_WORKDIR

#Run FastQC command
fastqc -t $NCPUS $arrayfile -o $FASTQC_OUT >& $FASTQC_OUT/$filebasename.log 2>&1
