#!/usr/bin/env bash
#PBS -N SamTools-flagstat-array_M
#PBS -q omp
#PBS -l select=1:ncpus=8:mem=20gb
#PBS -l walltime=00:30:00
#PBS -J 1-12


# Manage script history:
CB_NAME=$(basename $PBS_JOBNAME)
CB_LOG_FOLDER=$SCRATCH/"$CB_NAME"
mkdir -p $CB_LOG_FOLDER

# Set .log folder as the same as the script folder:
cd ${PBS_O_WORKDIR}

# Load samtools (Danecek _et al_., 2021) conda environment:
. /appli/bioinfo/samtools/1.9/env.sh

# Path to the aligned.bam reads from bwameth:
INBAM=$(ls /home/datawork-lex/pesto/methylseq/4-samtools/SamToolsSort_Roslin_M/*.bam | awk "NR==${PBS_ARRAY_INDEX}")
filebasename=$(basename ${INBAM%.bam})

# Running samtools Flagstat:
samtools flagstat -@ ${NCPUS} ${INBAM} > $CB_LOG_FOLDER/$filebasename.log 2>&1

# Unload samtools conda environment:
. /appli/bioinfo/samtools/1.9/delenv.sh
