#!/usr/bin/env bash
#PBS -N methyldackel_kit_trim_Roslin_G
#PBS -q omp
#PBS -l select=1:ncpus=10:mem=80gb
#PBS -l walltime=10:00:00
#PBS -J 1-12

# Manage script history:
CB_NAME=$(basename $PBS_JOBNAME)
CB_LOG_FOLDER=$SCRATCH/"$CB_NAME"
mkdir -p $CB_LOG_FOLDER

# Set .lof output folder as the same as the script folder:
cd ${PBS_O_WORKDIR}

# Load methyldackel (https://github.com/dpryan79/MethylDackel) conda environment:
. /appli/bioinfo/methyldackel/0.6.1/env.sh

# Path to the indexed reference genome:
REFERENCE=/home/datawork-lex/pesto/methylseq/3-bwameth/GCA_902806645.1_genomic.fna

# Path to the aligned_sort.bam files:
BAM=$(ls /home1/scratch/tsoldour/SamToolsSort_Roslin_G/*_sort.bam | awk "NR==${PBS_ARRAY_INDEX}")

# Path to the output folder:
OUT=$CB_LOG_FOLDER/$(basename ${BAM%_sort.bam})

# Run MathylDackel extract:
MethylDackel extract -@ ${NCPUS} ${REFERENCE} ${BAM} --minDepth 10 --methylKit --nOT 0,0,0,145 --nOB 0,0,9,0 -o ${OUT} > $CB_LOG_FOLDER/$CB_NAME.log 2>&1

# Unload methyldackel conda environment:
. /appli/bioinfo/methyldackel/0.6.1/delenv.sh
